### PR TITLE
Fixed Crashes, and bug

### PR DESCRIPTION
**Pull request by ErikPDev**
This commit should fix bugs mentioned on #16 
This also fixes a bug that gives you reward even if it was canceled.

### CODE REVIEW

**Comment by hamid0740** [comment]
Oh thanks
Btw I may check it in a test server to make sure if it works or not

**Comment by ErikPDev** [comment]
Returned the event if player is creative.

**Comment by ErikPDev** [comment]
I've tested the code, and another server owner. It works =D

**Comment by hamid0740** [comment]
> I've tested the code, and another server owner. It works =D

Thanks my friend, I will check the code by the arrival of my test server and finally update the plugin 😉

**Comment by hamid0740** [comment]
> Returned the event if player is creative.

Good but u see, some people who buy the ranks with the ability of changing game mode, sometimes wanna mine to have easy income, so I think this one is not related to the plugin writer, but related to the server owner.

**Review by ByPaps — CHANGES_REQUESTED** [review]
Sorry! The same problem still exists. I don't think it's just the fact of the priority change. The fixed, could collide with a series of plugins that prevent its natural functioning. What causes the error "Trying to access the offset of the array on a value of type bool"

**Comment by ErikPDev** [comment]
> Sorry! The same problem still exists. I don't think it's just the fact of the priority change. The fixed, could collide with a series of plugins that prevent its natural functioning. What causes the error "Trying to access the offset of the array on a value of type bool"

Have you tried the source from this branch? Hamid haven’t merged this pr with the master.

**Review by hamid0740 — APPROVED** [review]
Ok, thanks @ErikPDev for committing, I will add all of ur code suggestions except the line for disabling income from creative mode. I appreciate u again.

**Pull request merged**
